In [2]:
import numpy as np

a = np.array([1,2,3,4]) # 1 dimensi
print(a)
print(a[0])
print(a[1])

[1 2 3 4]
1
2


In [3]:
b = np.array([ # 2 dimensi
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(b)
print(b[0])
print(b[0][1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
2


In [5]:
c = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

print(c)
print(c[0])
print(c[0][0])
print(c[0][0][2])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1 2 3]
 [4 5 6]]
[1 2 3]
3


In [6]:
b = np.array([ # 2 dimensi
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(b.shape)
print(b.ndim)
print(b.size)

(3, 3)
2
9


ASSIGNMENT

In [3]:
import numpy as np

a = np.array([
    [10,20,30],
    [5,10,20],
    [2,4,6]
])

print(a)

[[10 20 30]
 [ 5 10 20]
 [ 2  4  6]]


In [4]:
b = np.array([
    [
        [10,11,12],
        [13,14,15],
        [16,17,18]
    ],
    [
        [20,21,22],
        [23,24,25],
        [26,27,28]
    ],
    [
        [30,31,32],
        [33,34,35],
        [36,37,38]
    ]

])

print(b)

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[20 21 22]
  [23 24 25]
  [26 27 28]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]]]


In [5]:
c = np.array([
    [
        ["MacBook", 3,"25jt"],
        ["Asus", 15, "11jt"],
        ["Hp",6,"8jt"]
    ],
    [
        ["iPhone", 5, "13jt"],
        ["Oppo", 22, "5jt"],
        ["Vivo",8,"4jt"]
    ]
])

print(c)
print(c.ndim)
print(c.shape)

[[['MacBook' '3' '25jt']
  ['Asus' '15' '11jt']
  ['Hp' '6' '8jt']]

 [['iPhone' '5' '13jt']
  ['Oppo' '22' '5jt']
  ['Vivo' '8' '4jt']]]
3
(2, 3, 3)


In [6]:
d = np.array([
    ["Raka", 21,"Badung","Programmer"],
    ["Bayu",22,"Denpasar","Web Developer"],
    ["Sri", 18,"Gianyar","Android Developer"],
    ["Dimas",30,"Gianyar","Data Analyst"]
])

print(d)
print(d.ndim)
print(d.shape)
print(d.size)

[['Raka' '21' 'Badung' 'Programmer']
 ['Bayu' '22' 'Denpasar' 'Web Developer']
 ['Sri' '18' 'Gianyar' 'Android Developer']
 ['Dimas' '30' 'Gianyar' 'Data Analyst']]
2
(4, 4)
16
