In [1]:
import numpy as np

a= np.array([10,20,30,40])

print(a[0])
print(a[0 : 3]) # [start : batas]

10
[10 20 30]


In [4]:
b = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

print(b[0][1])
print(b[0:, 0:2]) # [baris, kolom]

20
[[10 20]
 [40 50]
 [70 80]]


In [5]:
b = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

b[0] = [100,200,300]
b[1][1]=1000
print(b)

[[ 100  200  300]
 [  40 1000   60]
 [  70   80   90]]


ASSIGNMENT

In [7]:
c= np.array([
    ["Denis", "Scratch",8],
    ["Frank","Python", 18],
    ["Roger", "Unity", 15]
])

print(c[0])
print(c[1])
print(c[2])


['Denis' 'Scratch' '8']
['Frank' 'Python' '18']
['Roger' 'Unity' '15']


In [8]:
c= np.array([
    ["Denis", "Scratch",8],
    ["Frank","Python", 18],
    ["Roger", "Unity", 15]
])
print(c[0:, 0:2])

[['Denis' 'Scratch']
 ['Frank' 'Python']
 ['Roger' 'Unity']]


In [9]:
c= np.array([
    ["Denis", "Scratch",8],
    ["Frank","Python", 18],
    ["Roger", "Unity", 15]
])

c [0][1] = "Roblox"
print(c)

[['Denis' 'Roblox' '8']
 ['Frank' 'Python' '18']
 ['Roger' 'Unity' '15']]


In [10]:
d = np.array([
    ["Java","Richie",60,'C'],
    ["Python","Niels",80,'A'],
    ['R', "Brie",75,'B']
])

print(d[0])
print(d[1])
print(d[2])

['Java' 'Richie' '60' 'C']
['Python' 'Niels' '80' 'A']
['R' 'Brie' '75' 'B']


In [12]:
d = np.array([
    ["Java","Richie",60,'C'],
    ["Python","Niels",80,'A'],
    ['R', "Brie",75,'B']
])

print(d[0:,0:1])
print(d[0:,1:2])
print(d[0:,2:3])
print(d[0:,3:4])


[['Java']
 ['Python']
 ['R']]
[['Richie']
 ['Niels']
 ['Brie']]
[['60']
 ['80']
 ['75']]
[['C']
 ['A']
 ['B']]


In [13]:
d = np.array([
    ["Java","Richie",60,'C'],
    ["Python","Niels",80,'A'],
    ['R', "Brie",75,'B']
])

print(d[0:2])
print(d[0:,2:4])

[['Java' 'Richie' '60' 'C']
 ['Python' 'Niels' '80' 'A']]
[['60' 'C']
 ['80' 'A']
 ['75' 'B']]


In [15]:
d = np.array([
    ["Java","Richie",60,'C'],
    ["Python","Niels",80,'A'],
    ['R', "Brie",75,'B']
])
d[0:,0:1] = "Data Analyst"
print(d)

[['Data Analyst' 'Richie' '60' 'C']
 ['Data Analyst' 'Niels' '80' 'A']
 ['Data Analyst' 'Brie' '75' 'B']]


In [17]:
d = np.array([
    ["Java","Richie",60,'C'],
    ["Python","Niels",80,'A'],
    ['R', "Brie",75,'B']
])
d[2][2] = 90
d[2][3]= "A+"

print(d)

[['Java' 'Richie' '60' 'C']
 ['Python' 'Niels' '80' 'A']
 ['R' 'Brie' '90' 'A+']]


In [18]:
tampil = lambda a: print(a) # Lambda

tampil("hello")

hello


In [20]:
tambah1 = lambda a,b : a+b
tambah2 = lambda a,b : print(a+b)

hasil = tambah1 (10,20)
print(hasil)

tambah2(50,60)

30
110


In [21]:
tambah1 = (lambda a,b : a+b)(10,20)

print(tambah1)

30


In [25]:
def tambah(*a):
    total = 0
    for i in a :
        total += i
    return total

hasil = tambah(10,20,30,40,50)

rata =(lambda a : a / 5)(hasil)

print(hasil)
print(rata)

150
30.0
